### ISSUE TITLE
Error on right click

### ISSUE THREAD

**Issue by gschmidl** [gorbatiiivan/doslauncher#1]
When right clicking on any game, I get an Access violation error in doslauncher.exe.

64-bit version on the latest 64-bit Windows 10.

![image](https://user-images.githubusercontent.com/20334/131179577-10c4a73a-258b-4213-8113-f17a13b96970.png)

**Comment by gorbatiiivan** [comment]
Thank you, i testing only 32bit version.

**Comment by gorbatiiivan** [comment]
I fixed error, сan you please test it?

**Comment by gschmidl** [comment]
I will test it tomorrow, thank you!

**Comment by gschmidl** [comment]
Yes, it works now.
